### ISSUE TITLE
Сначала модель

### ISSUE THREAD

**Issue by Diaskhan** [jdtcn/RuntimeEfCore#1]
Слушай а такой вопрос !

А были задача генерировать сначала модель а потом код и скрипты миграции ?

Этот самый IDatabaseModelFactory ?

Если делать не реверс а строить сначала модель а потом выполнять миграции ? 

Подходит ли IDatabaseModelFactory?

**Comment by jdtcn** [comment]
Привет. Нет, я такого не делал. Теоретически для этого можно использовать выхлоп от IDatabaseModelFactory.

Но боюсь, что если применить сгенерированные миграции к базе, можно случайно её поломать.

**Comment by Diaskhan** [comment]
Я мог бы поделится наработками. Но там есть свои нюансы. Там немного по другому сделано.

Можно было объединить усилия. Потом на выходе получилось  бы Ef core web designer.

**Comment by Diaskhan** [comment]
Можно было объединить усилия. Потом на выходе сделали бы Ef core web designer.

**Comment by Diaskhan** [comment]
И да в том кейсе collectible assembly был бы кстати.

**Comment by jdtcn** [comment]
Спасибо за предложение, пока у меня нет планов развивать эту идею дальше: то что я хотел сделать уже работает.

Если есть код, которым можешь поделиться, то выкладывый, с удовольствием посмотрю.

**Comment by jdtcn** [comment]
[Monaco.zip](https://github.com/jdtcn/RuntimeEfCore/files/5236262/Monaco.zip)

**Comment by Diaskhan** [comment]
Привет.
Слушай а как запустить приложение ? 
это вроде просто либа ?

**Comment by jdtcn** [comment]
Да, это Razor Component Library, подключай к своему проекту, и пользуйся. В файле Editor.razor - пример использования, в файле Autocompleter.cs - пример сервиса для работы автокомплита.
