### ISSUE TITLE
Problem when upgrading project references

### ISSUE THREAD

**Issue by mirshahreza** [jdtcn/RuntimeEfCore#3]
Hi
I upgraded project to .Net 7 and then the references to the latest versions. after upgrading the code can not compile because of some errors and visual studio said you are missing some references. but when I downgrade the reference of microsoft.entityframeworkcore.design compile is successful but the program doesn't work correctly because of differences between versions.
Could you upgrade it to latest versions?
Thanks
Mohsen

**Comment by jdtcn** [comment]
Hi,

Indeed, there are some changes in NET 7, I updated the project, now everything should work as intended

**Comment by mirshahreza** [comment]
Upgrading to .Net 7 is ok but when you upgrade the EntityFramework references code can not compile

**Comment by mirshahreza** [comment]
![image](https://user-images.githubusercontent.com/2425566/201518391-405e7a4e-f34b-4a91-a0a4-4dcb8dfce3ee.png)
As you see there is some upgrade suggestion. when I upgrade packages code can not compile

**Comment by jdtcn** [comment]
Please clone the repository again, I've patched the code and updated the dependencies

**Comment by mirshahreza** [comment]
Thank you very much, 
It is ok :)
